name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch xlib.js from private repo
        run: |
          git clone https://${{ secrets.YOUR_TOKEN }}@github.com/<YOUR_NAME>/_blog.git
          cp _blog/xlib.js ./dist
          
      - name: Push to Pages
        working-directory: ./dist
        run: |
          git init
          git checkout -b gh-pages
          git add -A
          git commit -m 'Deploy website'
          git remote add origin https://${{ secrets.YOUR_TOKEN }}@github.com/<YOUR_NAME>/blog.git
          git push origin gh-pages -f -q
